//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EBNF.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_DLG_MCGETDATA               130
#define IDD_DLG_SETGET                  131
#define IDD_DLG_EVENT                   132
#define IDD_DLG_WC                      133
#define IDD_DLG_SET_WC_CONFIGURATION    134
#define IDD_DLG_SET_WC_PROFILE          135
#define IDD_DLG_SYSTEM                  136
#define IDD_DLG_COMPONENT_STATE         137
#define IDD_DIALOG_SHUTDOWN             138
#define IDD_DLG_VELOCITY_COUNTER        139
#define IDD_DLG_I2C_EPROM               140
#define IDD_DLG_I2C_TEMP                141
#define IDD_DLG_I2C_DP                  142
#define IDD_DLG_I2C_ADC                 143
#define IDC_BTN_MCGETDATA               1000
#define IDC_BTN_MCSETDATA               1001
#define IDC_EDT_MCSETDATA               1002
#define IDC_BTN_MCSTARTUP               1003
#define IDC_BTN_MCSETPROFILE            1004
#define IDC_BTN_MCINITIALIZE            1005
#define IDC_BTN_MCSTART                 1006
#define IDC_BTN_MCSTOP                  1007
#define IDC_BTN_MCGETDATAPACKAGE        1008
#define IDC_EDT_MCACTSTATE              1009
#define IDC_BTN_MCGETDATASTART          1010
#define IDC_EDT_MCNUMBER_OF_PACKAGE     1011
#define IDC_BTN_MC_TEST                 1012
#define IDC_EDT_LOGID                   1013
#define IDC_EDT_SETDWORD                1014
#define IDC_EDT_GETDWORD                1015
#define IDC_BTN_SETDWORD                1016
#define IDC_BTN_GETDWORD                1017
#define IDC_DLG_EVENT_OPEN_EVENT        1027
#define IDC_DLG_EVENT_CLOSE_EVENT       1028
#define IDC_DLG_EVENT_OPEN_EVENT_ID     1029
#define IDC_DLG_EVENT_CLOSE_EVENT_ID    1030
#define IDC_DLG_EVENT_POS               1031
#define IDC_DLG_EVENT_NEG               1032
#define IDC_EDT_WC_ACT_STATE            1033
#define IDC_BTN_WC_STARTUP              1034
#define IDC_BTN_WC_SETCONFIGURATION     1035
#define IDC_BTN_WC_SETPROFILE           1036
#define IDC_BTN_WC_INITIALIZE           1037
#define IDC_BTN_WC_REFERENCING          1038
#define IDC_BTN_WC_START                1039
#define IDC_BTN_WC_STOP                 1040
#define IDC_BTN_WC_PARK                 1041
#define IDC_BTN_WC_SHUTDOWN             1042
#define IDC_BTN_SETPROFILE              1044
#define IDC_BTN_SETCONFIG               1045
#define IDC_EDT_WC_1                    1046
#define IDC_EDT_WC_2                    1047
#define IDC_EDT_WC_3                    1048
#define IDC_EDT_WC_4                    1049
#define IDC_EDT_WC_5                    1050
#define IDC_EDT_WC_6                    1051
#define IDC_EDT_WC_7                    1052
#define IDC_EDT_WC_8                    1053
#define IDC_EDT_WC_9                    1054
#define IDC_EDT_WC_10                   1055
#define IDC_EDT_WC_11                   1056
#define IDC_EDT_WC_12                   1057
#define IDC_EDT_WC_13                   1058
#define IDC_EDT_WC_14                   1059
#define IDC_EDT_WC_15                   1060
#define IDC_EDT_WC_16                   1061
#define IDC_EDT_WC_17                   1062
#define IDC_EDT_WC_18                   1063
#define IDC_EDT_WC_19                   1064
#define IDC_EDT_WC_20                   1065
#define IDC_EDT_WC_21                   1066
#define IDC_EDT_WC_22                   1067
#define IDC_EDT_WC_23                   1068
#define IDC_EDT_WC_24                   1069
#define IDC_EDT_WC_25                   1070
#define IDC_BTN_WCCONFIG_SET_DEFAULT    1071
#define IDC_BTN_WCPROFILE_SET_DEFAULT   1072
#define IDC_BTN_SETGET_DWORD            1073
#define IDC_BTN_UPDATE_STATE            1074
#define IDC_BTN_SYS_CONNECTION_ESTABLISHED 1075
#define IDC_BTN_SYS_STARTUP             1076
#define IDC_BTN_SYS_START_DEVICE        1077
#define IDC_BTN_SYS_RESET_DEVICE        1078
#define IDC_BTN_SYS_CONNECTION_LOST     1079
#define IDC_BTN_SYS_SHUTDOWN            1080
#define IDC_BTN_SYS_READ_SW_VERSIONS    1082
#define IDC_BTN_SYS_DL_SW_COMP          1083
#define IDC_BTN_SYS_SET_IF_CONFIG       1084
#define IDC_BTN_SYS_DL_SW_TRACESYNC     1085
#define IDC_EDT_SYS_STATE               1086
#define IDC_EDT_SYS_CONN_STATE          1087
#define IDC_BTN_SYS_UPDATE_STATE        1088
#define IDC_BTN_PCI_WRITE               1089
#define IDC_BTN_PCI_READ                1090
#define IDC_EDT_PCI_ADR_WRITE           1091
#define IDC_EDT_PCI_VAL_WRITE           1092
#define IDC_EDT_PCI_ADR_READ            1093
#define IDC_EDT_PCI_VAL_READ            1094
#define IDC_DLG_SYSCP_DI                1095
#define IDC_BTN_SYS_COMPONENT_STATE     1096
#define IDC_DLG_SYSCP_ES                1097
#define IDC_DLG_SYSCP_I2CEPROM          1098
#define IDC_DLG_SYSCP_I2CIF             1099
#define IDC_DLG_SYSCP_I2TEMP            1100
#define IDC_DLG_SYSCP_MC                1101
#define IDC_RDO_PCI_ON                  1101
#define IDC_DLG_SYSCP_PC                1102
#define IDC_RDO_PCI_OFF                 1102
#define IDC_DLG_SYSCP_PO                1103
#define IDC_EDIT_VERSION                1103
#define IDC_DLG_SYSCP_ST                1104
#define IDC_BTN_SHOW_VELOCITY_COUNTER   1104
#define IDC_EDIT_OSVERSION              1104
#define IDC_DLG_SYSCP_TC                1105
#define IDC_EDT_WDG_POS                 1105
#define IDC_EDIT_IP_ADDRESS             1105
#define IDC_DLG_SYSCP_WC                1106
#define IDC_EDT_WDG_ACT_VLC             1106
#define IDC_CHECK1                      1107
#define IDC_EDT_WDG_LAST_VLC            1107
#define IDC_CHK_WRITE_FILE              1107
#define IDC_DLG_SYSCP_HI                1108
#define IDC_EDT_WDG_WDG_VOLT            1108
#define IDC_DLG_SYSCP_IO                1109
#define IDC_BTN_UPDATE_COUNTER          1109
#define IDC_DLG_SYSCP_I2CADC            1110
#define IDC_RDO_POS_DIR                 1110
#define IDC_DLG_SYSCP_I2CDP             1111
#define IDC_RDO_NEG_DIR                 1111
#define IDC_BTN_RESET_POSITION          1112
#define IDC_BTN_DAC_PWR_ON_OFF          1113
#define IDC_BTN_DAC_INI                 1113
#define IDC_BTN_DAC_EN                  1114
#define IDC_BTN_EMERGENCY_STOP          1115
#define IDC_BTN_LASER_ON                1116
#define IDC_RDO_PWR_ON                  1117
#define IDC_RDO_PWR_OFF                 1118
#define IDC_RDO_EN_ON                   1119
#define IDC_RDO_EN_OFF                  1120
#define IDC_RDO_LSR_ON                  1121
#define IDC_RDO_LSR_OFF                 1122
#define IDC_BTN_DAC_SET                 1123
#define IDC_BTN_DAC_CONTROLLER_ON_OFF   1124
#define IDC_RDO_CONTROLLER_ON           1125
#define IDC_RDN_READ                    1125
#define IDC_RDO_READ                    1125
#define IDC_RDO_CONTROLLER_OFF          1126
#define IDC_RDO_WRITE                   1126
#define IDC_BTN_LB                      1127
#define IDC_RDO_LASER_ON                1127
#define IDC_EDT_LB                      1128
#define IDC_RDO_LASER_OFF               1128
#define IDC_CHK_AUTO_UPDATE             1129
#define IDC_RDO_OSCI_ON                 1129
#define IDC_EDT_WDG_POS_INT             1130
#define IDC_RDO_OSCI_OFF                1130
#define IDC_BTN_WC_PID                  1131
#define IDC_BTN_WC_EMERGENCY_STOP       1134
#define IDC_BTN_LASER_ON_OFF            1135
#define IDC_BTN_WC_DAC_INI              1136
#define IDC_BTN_READ_BUFFER             1137
#define IDC_BTN_OSCI_ON_OFF             1138
#define IDC_BTN_TEST                    1139
#define IDC_BTN_ONLY_TEST               1139
#define IDC_EDT_TEST                    1141
#define IDC_BTN_EVENT                   1142
#define IDC_EDT_DEVICE_ID               1144
#define IDC_BTN_RD_BYTE                 1145
#define IDC_BTN_RD_PAGE                 1146
#define IDC_BTN_RD_CONTENT              1147
#define IDC_BTN_WR_BYTE                 1148
#define IDC_BTN_WR_BLOCK                1149
#define IDC_BTN_WR_CONTENT              1150
#define IDC_EDT_READ_VALUE              1151
#define IDC_EDT_BYTE_WRITE_VALUE        1152
#define IDC_EDT_PAGE_WRITE_VALUE        1153
#define IDC_EDT_READ_ADR_RB             1154
#define IDC_EDT_BYTE_WRITE_ADR_WB       1155
#define IDC_EDT_PAGE_WRITE_ADR_WB       1156
#define IDC_EDT_READ_ADR_RP             1157
#define IDC_EDT_NUMBEROFPAGES           1158
#define IDC_EDT_CONTENT_WRITE_VALUE     1159
#define IDC_BTN_GET_TEMP                1159
#define IDC_BTN_GET_CONFIG              1160
#define IDC_BTN_SET_CONFIG              1161
#define IDC_EDT_GET_TEMP                1162
#define IDC_EDT_GET_CONFIG              1163
#define IDC_RDO_CONTINOUS               1164
#define IDC_RDO_SINGLE                  1165
#define IDC_RDO_LOW                     1166
#define IDC_RDO_ABOVE_LOW               1167
#define IDC_RDO_NORMAL                  1168
#define IDC_RDO_HIGH                    1169
#define IDC_BTN_STARTUP                 1171
#define IDC_BTN_SHUTDOWN                1172
#define IDC_BTN_DP_WRITE                1173
#define IDC_BTN_DP_READ                 1174
#define IDC_EDT_DP_WRITE                1175
#define IDC_EDT_DP_READ                 1176
#define IDC_BTN_ADC_INI                 1177
#define IDC_BTN_ADC_GET_DATA            1178
#define IDC_EDT_ADC_AIN0                1179
#define IDC_EDT_ADC_AIN1                1180
#define IDC_EDT_ADC_AIN2                1181
#define IDC_BTN_FPGA_ARTNR              1181
#define IDC_EDT_ADC_AIN3                1182
#define IDC_BTN_FPGA_SWVERSION          1182
#define IDC_EDT_FPGA_ARTNR              1183
#define IDC_EDT_FPGA_SWVERSION          1184
#define IDC_EDIT_FPGA_VERSION           1185
#define IDD_DLG_TEST                    32771
#define IDD_DLG_SETGET_DWORD            32772
#define ID_TEST_EVENTS                  32773
#define ID_TEST_WEDGECONTROL            32774
#define TEST_SYSTEM                     32775
#define ID_TEST_I2CEPROM                32776
#define ID_TEST_I2CTEMPERATURE          32777
#define ID_TEST_I2CDP                   32778
#define ID_TEST_I2CADC                  32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1186
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
